// Stand-in for the ACHIEVEMENTS array that ticket 08 ships (N5 shipping list, achievements-draft.md).
// Tests only: the app reads the real global. Delete once 08 is merged and tests use it.
var ACHIEVEMENTS_FIXTURE = [
  { "id": "n5-all-lessons", "name": "Lesson Learned", "desc": "Pass every N5 lesson unit.", "category": "progress", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "n5-all-reviews", "name": "Déjà Vu All Over Again", "desc": "Pass every N5 review unit.", "category": "progress", "rarity": "uncommon", "hidden": false, "level": "n5" },
  { "id": "n5-prep", "name": "Strategy Session", "desc": "Finish the N5 test-prep block.", "category": "progress", "rarity": "uncommon", "hidden": false, "level": "n5" },
  { "id": "n5-clear", "name": "Go Go N5", "desc": "Clear every N5 unit.", "category": "progress", "rarity": "epic", "hidden": false, "level": "n5" },
  { "id": "n5-quiz-sweep", "name": "Hanamaru Garden", "desc": "Ace the quiz of every N5 unit.", "category": "quiz", "rarity": "legendary", "hidden": false, "level": "n5" },
  { "id": "n5-diagnostic", "name": "Jiko Shōkai", "desc": "Sit the N5 diagnostic.", "category": "mock", "rarity": "common", "hidden": false, "level": "n5" },
  { "id": "n5-mock-sat", "name": "Dress Rehearsal", "desc": "Sit a full N5 mock exam.", "category": "mock", "rarity": "common", "hidden": false, "level": "n5" },
  { "id": "n5-mock-pass", "name": "Gōkaku!", "desc": "Pass a full N5 mock (estimate).", "category": "mock", "rarity": "uncommon", "hidden": false, "level": "n5" },
  { "id": "n5-mock-pass-all", "name": "Double Gōkaku", "desc": "Pass every full N5 mock.", "category": "mock", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "n5-mock-honors", "name": "Gōkaku with Honors", "desc": "Score 80%+ on a full N5 mock, first try.", "category": "mock", "rarity": "epic", "hidden": false, "level": "n5" },
  { "id": "n5-mock-perfect", "name": "Zenmon Seikai", "desc": "Perfect score on a full N5 mock, first try.", "category": "mock", "rarity": "legendary", "hidden": false, "level": "n5" },
  { "id": "n5-mock-balanced", "name": "Four Corners", "desc": "80%+ in all four parts of one full N5 mock.", "category": "mock", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "n5-vocab-mature", "name": "Vocab Vault", "desc": "Every N5 vocab word is a real-mature card.", "category": "mastery", "rarity": "epic", "hidden": false, "level": "n5" },
  { "id": "n5-kanji-mature", "name": "Kanji Kaiser", "desc": "Every N5 kanji is a real-mature card.", "category": "mastery", "rarity": "epic", "hidden": false, "level": "n5" },
  { "id": "n5-grammar-mature", "name": "Particle Physicist", "desc": "Every N5 grammar point is a real-mature card.", "category": "mastery", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "n5-all-mature", "name": "Elephant Graveyard of Doubt", "desc": "Every N5 card is real-mature. (Konpurīto for memory.)", "category": "mastery", "rarity": "legendary", "hidden": false, "level": "n5" },
  { "id": "n5-hiragana", "name": "Hira-gone Wild", "desc": "Pass the hiragana units and their review.", "category": "progress", "rarity": "common", "hidden": false, "level": "n5" },
  { "id": "n5-katakana", "name": "Kata-strophe Averted", "desc": "Pass the katakana units and their review.", "category": "progress", "rarity": "common", "hidden": false, "level": "n5" },
  { "id": "hiragana-mastered", "name": "Hiragana Black Belt", "desc": "Every hiragana card real-mature.", "category": "mastery", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "katakana-mastered", "name": "Kata Master", "desc": "Every katakana card real-mature. (Kata: also a martial-arts form.)", "category": "mastery", "rarity": "rare", "hidden": false, "level": "n5" },
  { "id": "first-steps", "name": "Ichi Step at a Time", "desc": "Pass your first unit.", "category": "progress", "rarity": "common", "hidden": false, "level": null },
  { "id": "units-10", "name": "Jū-st Getting Started", "desc": "Pass 10 units.", "category": "progress", "rarity": "common", "hidden": false, "level": null },
  { "id": "units-25", "name": "Nijūgo Strong", "desc": "Pass 25 units.", "category": "progress", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "units-50", "name": "Gojū-on the Roll", "desc": "Pass 50 units.", "category": "progress", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "units-100", "name": "Hyaku Percent Effort", "desc": "Pass 100 units.", "category": "progress", "rarity": "rare", "hidden": false, "level": null },
  { "id": "hiragana-blitz", "name": "Zero to Hero in a Day", "desc": "Pass all ten hiragana units in one calendar day.", "category": "progress", "rarity": "rare", "hidden": true, "level": null, "revealed": "Did all of hiragana in a day." },
  { "id": "completionist", "name": "Konpurīto", "desc": "Unlock every other achievement.", "category": "progress", "rarity": "legendary", "hidden": true, "level": null, "revealed": "Unlocked everything. お疲れ様でした。" },
  { "id": "streak-4", "name": "Mikka Bōzu Breaker", "desc": "Study 4 days in a row. No three-day monk here.", "category": "habit", "rarity": "common", "hidden": false, "level": null },
  { "id": "streak-7", "name": "Isshūkan Ironclad", "desc": "7 days in a row.", "category": "habit", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "streak-30", "name": "Tsuki-ing With It", "desc": "30 days in a row.", "category": "habit", "rarity": "rare", "hidden": false, "level": null },
  { "id": "streak-100", "name": "Hyaku-nichi Hero", "desc": "100 days in a row.", "category": "habit", "rarity": "epic", "hidden": false, "level": null },
  { "id": "streak-365", "name": "Nen-stop", "desc": "Study every day for a year.", "category": "habit", "rarity": "legendary", "hidden": false, "level": null },
  { "id": "study-days-30", "name": "Thirty-Something", "desc": "Study on 30 different days.", "category": "habit", "rarity": "common", "hidden": false, "level": null },
  { "id": "study-days-100", "name": "Slow and Steady Kame", "desc": "100 different days.", "category": "habit", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "study-days-200", "name": "Kame Marathon", "desc": "200 different days.", "category": "habit", "rarity": "rare", "hidden": false, "level": null },
  { "id": "double-feature", "name": "Double Feature", "desc": "Pass 2 units in one calendar day.", "category": "habit", "rarity": "common", "hidden": false, "level": null },
  { "id": "hat-trick", "name": "Hat Trick", "desc": "Pass 3 units in one day.", "category": "habit", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "binge", "name": "Binge Watcher", "desc": "Pass 5 units in one day.", "category": "habit", "rarity": "rare", "hidden": false, "level": null },
  { "id": "comeback", "name": "Nana Korobi Ya Oki", "desc": "Fall down seven times, stand up eight.", "category": "habit", "rarity": "uncommon", "hidden": true, "level": null, "revealed": "Came back after a week+ away." },
  { "id": "early-bird", "name": "Hayaoki wa Sanmon no Toku", "desc": "Rise early, gain three mon.", "category": "habit", "rarity": "uncommon", "hidden": true, "level": null, "revealed": "Finished a quiz before 7 a.m." },
  { "id": "night-owl", "name": "Yoru no Fukurō", "desc": "Hoot hoot, hiragana.", "category": "habit", "rarity": "uncommon", "hidden": true, "level": null, "revealed": "Finished a quiz after midnight." },
  { "id": "new-year", "name": "Akemashite Omedetō", "desc": "Start the year with study.", "category": "habit", "rarity": "uncommon", "hidden": true, "level": null, "revealed": "Studied on New Year's Day." },
  { "id": "first-quiz", "name": "Pop Quiz Hot Shot", "desc": "Finish your first quiz.", "category": "quiz", "rarity": "common", "hidden": false, "level": null },
  { "id": "first-perfect", "name": "Hanamaru", "desc": "Ace a quiz. Have a flower circle. 💮", "category": "quiz", "rarity": "common", "hidden": false, "level": null },
  { "id": "perfect-10", "name": "Hanamaru Bouquet", "desc": "Ace the quiz of 10 different units.", "category": "quiz", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "perfect-50", "name": "Hanami Season", "desc": "Ace the quiz of 50 different units.", "category": "quiz", "rarity": "rare", "hidden": false, "level": null },
  { "id": "ippatsu", "name": "Ippatsu", "desc": "Ace 25 units on the very first attempt.", "category": "quiz", "rarity": "rare", "hidden": false, "level": null },
  { "id": "redemption-arc", "name": "Redemption Arc", "desc": "Struggle with a quiz, then come back and ace it.", "category": "quiz", "rarity": "uncommon", "hidden": true, "level": null, "revealed": "Aced a quiz you once scored under 60% on." },
  { "id": "mock-sittings-5", "name": "Mock-ingbird", "desc": "Sit 5 mock exams.", "category": "mock", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "mock-sittings-15", "name": "Mock Star", "desc": "Sit 15 mock exams.", "category": "mock", "rarity": "rare", "hidden": false, "level": null },
  { "id": "first-review", "name": "Flip Side", "desc": "Rate your first flashcard.", "category": "review", "rarity": "common", "hidden": false, "level": null },
  { "id": "reviews-100", "name": "Card Shark", "desc": "Review 100 cards.", "category": "review", "rarity": "common", "hidden": false, "level": null },
  { "id": "reviews-1000", "name": "Sen-bazuru", "desc": "Review 1,000 cards.", "category": "review", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "reviews-5000", "name": "Go-sen Flips", "desc": "Review 5,000 cards.", "category": "review", "rarity": "epic", "hidden": false, "level": null },
  { "id": "review-day-50", "name": "Zen Deck", "desc": "Rate 50 cards in one calendar day.", "category": "review", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "review-day-100", "name": "Marathon Mōdo", "desc": "Rate 100 cards in one calendar day.", "category": "review", "rarity": "rare", "hidden": false, "level": null },
  { "id": "mature-1", "name": "Graduation Day", "desc": "Grow a card to a 21-day interval.", "category": "review", "rarity": "common", "hidden": false, "level": null },
  { "id": "mature-100", "name": "Long-Term Memory Lane", "desc": "100 real-mature cards.", "category": "review", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "mature-500", "name": "Elephants Never Wasureru", "desc": "500 real-mature cards.", "category": "review", "rarity": "epic", "hidden": false, "level": null },
  { "id": "interval-365", "name": "Mata Rainen", "desc": "A card scheduled a full year out.", "category": "review", "rarity": "rare", "hidden": false, "level": null },
  { "id": "import-first", "name": "Head Start", "desc": "Mark something as already known.", "category": "review", "rarity": "common", "hidden": false, "level": null },
  { "id": "import-proved", "name": "Told You So", "desc": "25 known cards that passed their first real test.", "category": "review", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "kanji-mature-25", "name": "Kanji-nator", "desc": "25 real-mature kanji cards.", "category": "mastery", "rarity": "uncommon", "hidden": false, "level": null },
  { "id": "kanji-mature-50", "name": "Radical Behavior", "desc": "50 real-mature kanji cards.", "category": "mastery", "rarity": "rare", "hidden": false, "level": null }
];
