#!/usr/bin/env node
/**
 * Generates sw.js (the service worker) from the files the app ships.
 * Zero-dep. Run from anywhere: node tools/build-sw.js   (rerun after adding or changing ANY shipped file)
 *
 * Precache list = index.html + every <script src>/<link href> in it + manifest.webmanifest
 *               + icons/ + sfx/*.mp3|ogg + kanji-svg/*.svg. audio/manifest.js is precached as a script;
 *               audio/*.mp3 (listening clips, ~7 MB) are NOT: RUNTIME_ONLY, cached on first play. All URLs are relative (no leading slash)
 *               so the same tree works at a host root and under a subpath.
 * Cache version = sha256 over the sw template + each file's path and content (text files with
 *               CRLF normalised so Windows/Linux checkouts agree), first 12 hex chars.
 * Exports build(root) -> { files, version, source } for run-tests.js.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// Shipped but deliberately not precached: the service worker caches these on first request (cache-first,
// cache AUDIO_CACHE, which activate never deletes). run-tests.js checks the list against the files on disk.
const RUNTIME_ONLY = /^audio\/[^\/]+\.mp3$/;

const TEXT = /\.(js|css|html|svg|webmanifest|json|txt|md)$/;

function walk(root, dir, re) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs).sort().filter(function (f) { return re.test(f); }).map(function (f) { return dir + "/" + f; });
}

function listFiles(root) {
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const refs = [];
  html.replace(/<(?:script[^>]*\ssrc|link[^>]*\shref)="([^"]+)"/g, function (_, u) { refs.push(u); });
  const set = ["index.html", "manifest.webmanifest"].concat(refs)
    .concat(walk(root, "icons", /\.(png|svg)$/), walk(root, "sfx", /\.(mp3|ogg)$/), walk(root, "kanji-svg", /\.svg$/),
      // licence files: Settings links them, so they must open offline too
      walk(root, "vendor", /^LICENSE/), walk(root, "sfx", /^LICENSE/), walk(root, "kanji-svg", /^LICENSE/));
  return Array.from(new Set(set)).sort();
}

const TEMPLATE = [
  "// GENERATED by tools/build-sw.js: do not edit by hand. Rerun it after adding or changing any shipped file.",
  "var CACHE = 'jelly-%VERSION%';",
  "var AUDIO_CACHE = 'jelly-audio-v1'; // stable name: survives app updates, holds listening clips cached on first play",
  "var FILES = %FILES%;",
  "self.addEventListener('install', function (e) {",
  "  // No skipWaiting here: the app decides when to apply an update (never mid-quiz).",
  "  e.waitUntil(caches.open(CACHE).then(function (c) {",
  "    return c.addAll(FILES.map(function (u) { return new Request(u, { cache: 'reload' }); }));",
  "  }));",
  "});",
  "self.addEventListener('message', function (e) { if (e.data === 'SKIP_WAITING') self.skipWaiting(); });",
  "self.addEventListener('activate', function (e) {",
  "  e.waitUntil(caches.keys().then(function (ks) {",
  "    return Promise.all(ks.filter(function (k) { return k !== CACHE && k !== AUDIO_CACHE; }).map(function (k) { return caches.delete(k); }));",
  "  }).then(function () { return self.clients.claim(); }));",
  "});",
  "self.addEventListener('fetch', function (e) {",
  "  var r = e.request, u = new URL(r.url);",
  "  // Same-origin GET only: CouchDB sync and any other cross-origin request go straight to the network.",
  "  if (r.method !== 'GET' || u.origin !== self.location.origin) return;",
  "  // Listening clips (audio/*.mp3): cache-first in their own cache, filled on first play. Whole 200 responses",
  "  // only (a Range request or a 206 can't be cached); offline and uncached = network error, the page falls back.",
  "  if (/\\/audio\\/[^\\/]+\\.mp3$/.test(u.pathname) && !r.headers.has('range')) {",
  "    e.respondWith(caches.open(AUDIO_CACHE).then(function (c) {",
  "      return c.match(r).then(function (hit) {",
  "        return hit || fetch(r).then(function (res) { if (res.status === 200) c.put(r, res.clone()); return res; });",
  "      });",
  "    }));",
  "    return;",
  "  }",
  "  e.respondWith(caches.open(CACHE).then(function (c) {",
  "    return c.match(r).then(function (hit) {",
  "      return hit || (r.mode === 'navigate' ? c.match('index.html') : null) || fetch(r);",
  "    });",
  "  }));",
  "});",
  ""
].join("\n");

function build(root) {
  const files = listFiles(root);
  const h = crypto.createHash("sha256").update(TEMPLATE);
  files.forEach(function (f) {
    let buf = fs.readFileSync(path.join(root, f));
    if (TEXT.test(f)) buf = Buffer.from(buf.toString("utf8").replace(/\r\n/g, "\n"));
    h.update("\0" + f + "\0").update(buf);
  });
  const version = h.digest("hex").slice(0, 12);
  const source = TEMPLATE.replace("%VERSION%", version).replace("%FILES%", function () { return JSON.stringify(files, null, 2); });
  return { files: files, version: version, source: source };
}

module.exports = { build: build, RUNTIME_ONLY: RUNTIME_ONLY };

if (require.main === module) {
  const root = path.resolve(__dirname, "..");
  const out = build(root);
  fs.writeFileSync(path.join(root, "sw.js"), out.source);
  console.log("sw.js: " + out.files.length + " files, version " + out.version);
}
